modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "projectk"
version = "${version}"
displayName = "ProjectK"
authors = "Hashibutogarasu"
description = '''

'''
#logoFile = ""

[[dependencies.projectk]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.projectk]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.projectk]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.projectk]]
modId="guideme"
type="required"
versionRange="[21.1,21.1.15)"
ordering="NONE"
side="BOTH"

[[dependencies.projectk]]
modId="create"
type="optional"
versionRange="[6.0.9,6.1.0)"
ordering="NONE"
side="BOTH"

[[dependencies.projectk]]
modId="mekanism"
type="optional"
versionRange="[10.7,)"
ordering="NONE"
side="BOTH"

[[dependencies.projectk]]
modId="projecte"
type="optional"
versionRange="[1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.projectk]]
modId="rei"
type="optional"
versionRange="[16.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.projectk]]
modId="karasucore"
type="required"
versionRange="[0.0.1-SNAPSHOT,)"
ordering="NONE"
side="BOTH"

[[mixins]]
config = "projectk.mixins.json"
