modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "Unlicense"

[[mods]]
modId = "projectk"
version = "${version}"
displayName = "ProjectK"
authors = "Hashibutogarasu"
description = '''

'''
#logoFile = ""

[[dependencies.projectk]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.projectk]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.projectk]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "projectk.mixins.json"
